// Catalog seed — a faithful TypeScript mirror of the frontend's js/data.js
// (BumiData.BRANDS + BumiData.PRODUCTS). Prices are AUD dollars (multiplied to
// cents in seed.ts). Source spreadsheet:
// indonesia_kidswear_top_sellers_revised_2026-07-15.xlsx (3 brands, 15 products).

export type Audience = "GIRLS" | "BOYS" | "BABY" | "UNISEX";
export type ProductType = "TSHIRTS" | "SHORTS" | "DRESSES" | "OUTERWEAR" | "ACCESSORIES" | "BABY";
export type Badge = "NEW" | "BESTSELLER" | "SALE";

export interface SeedColor {
  name: string;
  hex: string;
}

export interface SeedBrand {
  slug: string;
  name: string;
  city: string;
  audience: Audience;
  website: string;
  desc: string;
}

export interface SeedProduct {
  id: string; // becomes Product.slug
  name: string;
  brand: string; // brand name (resolved to brandId in seed.ts)
  audience: Audience;
  category: ProductType;
  price: number; // AUD dollars, GST-inclusive
  compareAt?: number; // AUD dollars
  fibre: string;
  colors: SeedColor[];
  sizes: string[];
  image: string;
  gallery: string[];
  badge: Badge | null;
  isNew: boolean;
  isBestseller: boolean;
  rating: number;
  reviews: number;
  addedAt: number;
  description: string;
  material: string;
}

export const BRANDS: SeedBrand[] = [
  {
    slug: "bohopanna",
    name: "Bohopanna",
    city: "Indonesia",
    audience: "GIRLS",
    website: "https://bohopanna.com/",
    desc: "Playful, comfy everyday kidswear in soft natural tones — breezy sets, easy tees and go-anywhere pants for little explorers.",
  },
  {
    slug: "sabine-heem",
    name: "Sabine & Heem",
    city: "Indonesia",
    audience: "BOYS",
    website: "https://www.sabineandheem.com/",
    desc: "Considered linen and cotton pieces with hand-finished embroidery. Slow-made staples for kids with quiet, confident style.",
  },
  {
    slug: "anakmu",
    name: "Anakmu",
    city: "Indonesia",
    audience: "UNISEX",
    website: "https://shopee.co.id/anakmu.id",
    desc: "Soft, premium basics — fleece sweaters, organic tees and easy layers designed to mix, match and pass down.",
  },
];

export const PRODUCTS: SeedProduct[] = [
  {
    id: "elliot-pant",
    name: "Elliot Pant",
    brand: "Bohopanna",
    audience: "UNISEX",
    category: "SHORTS",
    price: 15,
    fibre: "Cotton twill",
    colors: [
      { name: "Khaki", hex: "#B9A88A" },
      { name: "Black", hex: "#333333" },
      { name: "Stone", hex: "#C9BBA7" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6"],
    image: "images/categories/trousers.png",
    gallery: ["images/categories/trousers.png", "images/categories/kids.png"],
    badge: "BESTSELLER",
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviews: 312,
    addedAt: 15,
    description: "Bohopanna's most-loved everyday pant — an easy pull-on shape with a comfy elastic waist, built for playground days.",
    material: "100% cotton twill. Machine wash cold.",
  },
  {
    id: "basic-tee-girl",
    name: "Basic Tee Girl",
    brand: "Bohopanna",
    audience: "GIRLS",
    category: "TSHIRTS",
    price: 9,
    compareAt: 12,
    fibre: "Cotton jersey",
    colors: [
      { name: "Sunny Peach", hex: "#F9B8AF" },
      { name: "Sky Blue", hex: "#96ADD6" },
      { name: "White", hex: "#FFFFFF" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6"],
    image: "images/categories/kids.png",
    gallery: ["images/categories/kids.png"],
    badge: "NEW",
    isNew: true,
    isBestseller: false,
    rating: 4.9,
    reviews: 208,
    addedAt: 14,
    description: "A soft, tag-free cotton tee in cheerful colours — the everyday top she'll reach for all week.",
    material: "100% cotton jersey. Machine wash cold.",
  },
  {
    id: "pannadaily-set-girl",
    name: "Pannadaily Set Kids Girl Print",
    brand: "Bohopanna",
    audience: "GIRLS",
    category: "DRESSES",
    price: 12,
    fibre: "Cotton",
    colors: [
      { name: "Print", hex: "#F9B8AF" },
      { name: "Pink", hex: "#F2D7D3" },
    ],
    sizes: ["2T", "3T", "4T", "5"],
    image: "images/categories/dresses.png",
    gallery: ["images/categories/dresses.png", "images/categories/kids.png"],
    badge: null,
    isNew: false,
    isBestseller: false,
    rating: 4.9,
    reviews: 156,
    addedAt: 13,
    description: "A breezy two-piece set in a playful print — ready in one grab for school mornings and weekend trips.",
    material: "100% cotton. Machine wash cold.",
  },
  {
    id: "pannadaily-playsuit",
    name: "Pannadaily Playsuit Girl Print",
    brand: "Bohopanna",
    audience: "BABY",
    category: "BABY",
    price: 12,
    fibre: "Cotton",
    colors: [
      { name: "Print", hex: "#F2D7D3" },
      { name: "Cream", hex: "#F7F3EE" },
    ],
    sizes: ["6-12M", "12-18M", "18-24M"],
    image: "images/categories/baby.png",
    gallery: ["images/categories/baby.png", "images/categories/kids.png"],
    badge: null,
    isNew: false,
    isBestseller: false,
    rating: 4.9,
    reviews: 98,
    addedAt: 12,
    description: "A snuggly printed playsuit with snap closures for easy changes. Comfy enough to crawl, cute enough for photos.",
    material: "100% cotton. Machine wash cold.",
  },
  {
    id: "barrel-jeans",
    name: "Barrel Jeans",
    brand: "Bohopanna",
    audience: "UNISEX",
    category: "SHORTS",
    price: 29,
    compareAt: 39,
    fibre: "Cotton denim",
    colors: [
      { name: "Denim", hex: "#6E8AC0" },
      { name: "Indigo", hex: "#00408C" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6", "7"],
    image: "images/categories/trousers.png",
    gallery: ["images/categories/trousers.png", "images/categories/kids.png"],
    badge: "SALE",
    isNew: false,
    isBestseller: false,
    rating: 4.9,
    reviews: 142,
    addedAt: 11,
    description: "On-trend barrel-leg jeans in soft denim with a touch of stretch — tough enough for adventures, easy to move in.",
    material: "Cotton denim with elastane. Machine wash cold.",
  },
  {
    id: "horse-linen-sashiko-shirt",
    name: "HORSE Linen Sashiko Shirt",
    brand: "Sabine & Heem",
    audience: "BOYS",
    category: "TSHIRTS",
    price: 39,
    fibre: "Linen",
    colors: [
      { name: "Natural", hex: "#EADFD3" },
      { name: "Black", hex: "#333333" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6"],
    image: "images/categories/kids.png",
    gallery: ["images/categories/kids.png"],
    badge: "BESTSELLER",
    isNew: false,
    isBestseller: true,
    rating: 5.0,
    reviews: 187,
    addedAt: 10,
    description: "A breathable linen shirt with hand-finished sashiko stitching — slow-made polish for special everyday days.",
    material: "100% linen. Machine wash cold.",
  },
  {
    id: "howdy-embroidery-tee",
    name: "HOWDY Embroidery Tee",
    brand: "Sabine & Heem",
    audience: "BOYS",
    category: "TSHIRTS",
    price: 39,
    fibre: "Cotton",
    colors: [
      { name: "Cream", hex: "#F7F3EE" },
      { name: "Blue", hex: "#96ADD6" },
    ],
    sizes: ["2T", "3T", "4T", "5"],
    image: "images/categories/kids.png",
    gallery: ["images/categories/kids.png"],
    badge: null,
    isNew: false,
    isBestseller: false,
    rating: 4.9,
    reviews: 76,
    addedAt: 9,
    description: "A soft cotton tee with cheerful HOWDY embroidery. Laid-back, durable and made to last.",
    material: "100% cotton. Machine wash cold.",
  },
  {
    id: "wonder-linen-shirt-black",
    name: "WONDER Embroidery Linen Shirt — Black",
    brand: "Sabine & Heem",
    audience: "BOYS",
    category: "TSHIRTS",
    price: 39,
    fibre: "Linen",
    colors: [{ name: "Black", hex: "#333333" }],
    sizes: ["2T", "3T", "4T", "5", "6"],
    image: "images/categories/kids.png",
    gallery: ["images/categories/kids.png"],
    badge: null,
    isNew: false,
    isBestseller: false,
    rating: 5.0,
    reviews: 64,
    addedAt: 8,
    description: "A classic linen shirt in black with embroidered detail — cool, crisp and endlessly versatile.",
    material: "100% linen. Machine wash cold.",
  },
  {
    id: "na-willa-knitted-vest",
    name: "NA WILLA Cotton Knitted Collar Vest — Polkadot",
    brand: "Sabine & Heem",
    audience: "GIRLS",
    category: "OUTERWEAR",
    price: 49,
    fibre: "Cotton knit",
    colors: [
      { name: "Polkadot", hex: "#F2D7D3" },
      { name: "Cream", hex: "#F7F3EE" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6"],
    image: "images/categories/outerwear.png",
    gallery: ["images/categories/outerwear.png", "images/categories/kids.png"],
    badge: null,
    isNew: false,
    isBestseller: false,
    rating: 5.0,
    reviews: 41,
    addedAt: 7,
    description: "A cotton knitted collar vest in a sweet polkadot knit — a layered finishing piece with handmade charm.",
    material: "100% cotton knit. Machine wash cold.",
  },
  {
    id: "wonder-linen-shirt-white",
    name: "WONDER Embroidery Linen Shirt — Broken White",
    brand: "Sabine & Heem",
    audience: "BOYS",
    category: "TSHIRTS",
    price: 39,
    fibre: "Linen",
    colors: [{ name: "Broken White", hex: "#F2EEE9" }],
    sizes: ["2T", "3T", "4T", "5", "6"],
    image: "images/categories/kids.png",
    gallery: ["images/categories/kids.png"],
    badge: null,
    isNew: false,
    isBestseller: false,
    rating: 5.0,
    reviews: 58,
    addedAt: 6,
    description: "The WONDER linen shirt in broken white — warm, neutral and easy to pair with anything.",
    material: "100% linen. Machine wash cold.",
  },
  {
    id: "piccolo-jacket",
    name: "Piccolo Jacket",
    brand: "Anakmu",
    audience: "UNISEX",
    category: "OUTERWEAR",
    price: 35,
    compareAt: 45,
    fibre: "Polyester",
    colors: [
      { name: "Navy", hex: "#00408C" },
      { name: "Slate", hex: "#8A8A8A" },
      { name: "Cream", hex: "#F2EEE9" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6", "7", "8"],
    image: "images/categories/outerwear.png",
    gallery: ["images/categories/outerwear.png", "images/categories/kids.png"],
    badge: "BESTSELLER",
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviews: 421,
    addedAt: 5,
    description: "A lightweight premium-polyester windbreaker that shrugs off wind and light rain. Packs small for day trips.",
    material: "Premium polyester shell. Machine wash cold.",
  },
  {
    id: "torena-sweater",
    name: "Torena Sweater — Plain Basic",
    brand: "Anakmu",
    audience: "UNISEX",
    category: "OUTERWEAR",
    price: 29,
    fibre: "Cotton fleece",
    colors: [
      { name: "Grey", hex: "#8A8A8A" },
      { name: "Cream", hex: "#F2EEE9" },
      { name: "Navy", hex: "#00408C" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6", "7", "8"],
    image: "images/categories/outerwear.png",
    gallery: ["images/categories/outerwear.png", "images/categories/kids.png"],
    badge: "BESTSELLER",
    isNew: false,
    isBestseller: true,
    rating: 4.9,
    reviews: 388,
    addedAt: 4,
    description: "A super-soft premium fleece sweater in a plain, go-with-everything colour — cosy layering, made to last.",
    material: "100% cotton fleece. Machine wash cold.",
  },
  {
    id: "gufi-rib-sweater",
    name: "Gufi Rib Sweater — Plain Basic",
    brand: "Anakmu",
    audience: "UNISEX",
    category: "OUTERWEAR",
    price: 29,
    fibre: "Cotton knit",
    colors: [
      { name: "Grey", hex: "#8A8A8A" },
      { name: "Peach", hex: "#F9B8AF" },
    ],
    sizes: ["2T", "3T", "4T", "5"],
    image: "images/categories/outerwear.png",
    gallery: ["images/categories/outerwear.png", "images/categories/kids.png"],
    badge: null,
    isNew: false,
    isBestseller: false,
    rating: 4.9,
    reviews: 134,
    addedAt: 3,
    description: "A fine cotton-knit sweater with a subtle rib texture — lightweight warmth for in-between weather.",
    material: "100% cotton knit. Machine wash cold.",
  },
  {
    id: "organic-pocket-tee",
    name: "Organic Pocket T-Shirt — Basic",
    brand: "Anakmu",
    audience: "UNISEX",
    category: "TSHIRTS",
    price: 12,
    fibre: "Organic cotton",
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Navy", hex: "#00408C" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6", "7"],
    image: "images/categories/kids.png",
    gallery: ["images/categories/kids.png"],
    badge: "NEW",
    isNew: true,
    isBestseller: false,
    rating: 4.9,
    reviews: 263,
    addedAt: 2,
    description: "A GOTS-organic cotton tee with a handy chest pocket — the blank-basic top that goes with everything.",
    material: "GOTS-organic cotton. Machine wash cold.",
  },
  {
    id: "brisa-cargo-pants",
    name: "Brisa Cargo Pants",
    brand: "Anakmu",
    audience: "UNISEX",
    category: "SHORTS",
    price: 25,
    fibre: "Cotton blend",
    colors: [
      { name: "Khaki", hex: "#B9A88A" },
      { name: "Black", hex: "#333333" },
    ],
    sizes: ["2T", "3T", "4T", "5", "6"],
    image: "images/categories/trousers.png",
    gallery: ["images/categories/trousers.png", "images/categories/kids.png"],
    badge: null,
    isNew: false,
    isBestseller: false,
    rating: 4.9,
    reviews: 119,
    addedAt: 1,
    description: "Easy cargo pants with roomy pockets, built for kids on the move. Unisex fit for ages 1–7.",
    material: "Cotton blend. Machine wash cold.",
  },
];

// Nav/landing categories (the slugs the storefront's filterByCategory understands).
// Mirrors the keys of BumiData.categoryMeta + the product-type leaves.
export const NAV_CATEGORY_SLUGS = [
  "girls",
  "boys",
  "baby",
  "women",
  "new",
  "sale",
  "bestsellers",
  "essentials",
  "kids",
  "all",
  "tshirts",
  "shorts",
  "dresses",
  "outerwear",
  "accessories",
] as const;

export const NAV_CATEGORY_LABELS: Record<string, string> = {
  girls: "Girls' Collection",
  boys: "Boys' Collection",
  baby: "Baby Collection",
  women: "Women's Casual",
  new: "New This Week",
  sale: "On Sale",
  bestsellers: "Bestsellers",
  essentials: "Everyday Essentials",
  kids: "Kids' Collection",
  all: "All Kids' Clothing",
  tshirts: "T-Shirts",
  shorts: "Shorts & Pants",
  dresses: "Dresses & Sets",
  outerwear: "Outerwear",
  accessories: "Accessories",
};
